
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #  通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # 通过eureka.client.defaultZone声明所有module的注册中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server